-- Reversão de 20260908120000_freeze_deferred_domains.sql
--
-- NÃO é migration: fica fora de migrations/ e não roda em `supabase db reset`.
-- Rodar só para desfazer o congelamento em produção, se ele for aplicado e precisar voltar.
--
-- Gerado em 2026-09-14 a partir do banco vivo (projeto eplivpvqemowmbivhfpx), ANTES do
-- congelamento: é o estado exato de RLS, políticas e grants das 44 tabelas congeladas.
--
--   44 drop policy (*_frozen_deny_all)
--   44 alter table (estado de RLS; todas já tinham RLS ligado)
--   170 create policy (as políticas que o congelamento remove)
--   88 grant (os grants de anon e authenticated que o congelamento revoga)

begin;

drop policy if exists club_entries_frozen_deny_all on public.club_entries;
drop policy if exists club_check_in_outs_frozen_deny_all on public.club_check_in_outs;
drop policy if exists club_birthday_entries_frozen_deny_all on public.club_birthday_entries;
drop policy if exists guest_list_entries_frozen_deny_all on public.guest_list_entries;
drop policy if exists lineups_frozen_deny_all on public.lineups;
drop policy if exists lineup_slots_frozen_deny_all on public.lineup_slots;
drop policy if exists promoters_frozen_deny_all on public.promoters;
drop policy if exists promoter_sales_frozen_deny_all on public.promoter_sales;
drop policy if exists promoter_payments_frozen_deny_all on public.promoter_payments;
drop policy if exists vip_table_reservations_frozen_deny_all on public.vip_table_reservations;
drop policy if exists vip_table_guests_frozen_deny_all on public.vip_table_guests;
drop policy if exists vip_table_tabs_frozen_deny_all on public.vip_table_tabs;
drop policy if exists vip_table_tab_items_frozen_deny_all on public.vip_table_tab_items;
drop policy if exists queue_entries_frozen_deny_all on public.queue_entries;
drop policy if exists tabs_frozen_deny_all on public.tabs;
drop policy if exists tab_items_frozen_deny_all on public.tab_items;
drop policy if exists tab_members_frozen_deny_all on public.tab_members;
drop policy if exists tab_payments_frozen_deny_all on public.tab_payments;
drop policy if exists ingredients_frozen_deny_all on public.ingredients;
drop policy if exists ingredient_prices_frozen_deny_all on public.ingredient_prices;
drop policy if exists ingredient_suppliers_frozen_deny_all on public.ingredient_suppliers;
drop policy if exists suppliers_frozen_deny_all on public.suppliers;
drop policy if exists supplier_item_mappings_frozen_deny_all on public.supplier_item_mappings;
drop policy if exists recipes_frozen_deny_all on public.recipes;
drop policy if exists recipe_ingredients_frozen_deny_all on public.recipe_ingredients;
drop policy if exists drink_recipes_frozen_deny_all on public.drink_recipes;
drop policy if exists stock_items_frozen_deny_all on public.stock_items;
drop policy if exists stock_movements_frozen_deny_all on public.stock_movements;
drop policy if exists inventory_counts_frozen_deny_all on public.inventory_counts;
drop policy if exists inventory_count_items_frozen_deny_all on public.inventory_count_items;
drop policy if exists inventory_items_frozen_deny_all on public.inventory_items;
drop policy if exists purchase_records_frozen_deny_all on public.purchase_records;
drop policy if exists unit_conversions_frozen_deny_all on public.unit_conversions;
drop policy if exists shifts_frozen_deny_all on public.shifts;
drop policy if exists attendances_frozen_deny_all on public.attendances;
drop policy if exists leave_requests_frozen_deny_all on public.leave_requests;
drop policy if exists platform_connections_frozen_deny_all on public.platform_connections;
drop policy if exists external_menu_mappings_frozen_deny_all on public.external_menu_mappings;
drop policy if exists delivery_settlements_frozen_deny_all on public.delivery_settlements;
drop policy if exists restaurant_integrations_frozen_deny_all on public.restaurant_integrations;
drop policy if exists webhook_subscriptions_frozen_deny_all on public.webhook_subscriptions;
drop policy if exists webhook_deliveries_frozen_deny_all on public.webhook_deliveries;
drop policy if exists waiter_calls_frozen_deny_all on public.waiter_calls;
drop policy if exists payment_splits_frozen_deny_all on public.payment_splits;

alter table public.attendances enable row level security;
alter table public.club_birthday_entries enable row level security;
alter table public.club_check_in_outs enable row level security;
alter table public.club_entries enable row level security;
alter table public.delivery_settlements enable row level security;
alter table public.drink_recipes enable row level security;
alter table public.external_menu_mappings enable row level security;
alter table public.guest_list_entries enable row level security;
alter table public.ingredient_prices enable row level security;
alter table public.ingredient_suppliers enable row level security;
alter table public.ingredients enable row level security;
alter table public.inventory_count_items enable row level security;
alter table public.inventory_counts enable row level security;
alter table public.inventory_items enable row level security;
alter table public.leave_requests enable row level security;
alter table public.lineup_slots enable row level security;
alter table public.lineups enable row level security;
alter table public.payment_splits enable row level security;
alter table public.platform_connections enable row level security;
alter table public.promoter_payments enable row level security;
alter table public.promoter_sales enable row level security;
alter table public.promoters enable row level security;
alter table public.purchase_records enable row level security;
alter table public.queue_entries enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.recipes enable row level security;
alter table public.restaurant_integrations enable row level security;
alter table public.shifts enable row level security;
alter table public.stock_items enable row level security;
alter table public.stock_movements enable row level security;
alter table public.supplier_item_mappings enable row level security;
alter table public.suppliers enable row level security;
alter table public.tab_items enable row level security;
alter table public.tab_members enable row level security;
alter table public.tab_payments enable row level security;
alter table public.tabs enable row level security;
alter table public.unit_conversions enable row level security;
alter table public.vip_table_guests enable row level security;
alter table public.vip_table_reservations enable row level security;
alter table public.vip_table_tab_items enable row level security;
alter table public.vip_table_tabs enable row level security;
alter table public.waiter_calls enable row level security;
alter table public.webhook_deliveries enable row level security;
alter table public.webhook_subscriptions enable row level security;
create policy authenticated_delete_by_restaurant_manager on public.attendances as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.attendances as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.attendances as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.attendances as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.attendances as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.attendances as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.attendances as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.attendances as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.club_birthday_entries as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.club_birthday_entries as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.club_birthday_entries as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.club_birthday_entries as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.club_birthday_entries as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.club_birthday_entries as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.club_birthday_entries as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.club_birthday_entries as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.club_check_in_outs as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.club_check_in_outs as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.club_check_in_outs as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.club_check_in_outs as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.club_check_in_outs as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.club_check_in_outs as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.club_check_in_outs as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.club_check_in_outs as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.club_entries as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.club_entries as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.club_entries as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.club_entries as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.club_entries as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.club_entries as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.club_entries as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.club_entries as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.delivery_settlements as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.delivery_settlements as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.delivery_settlements as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.delivery_settlements as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.drink_recipes as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.drink_recipes as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.drink_recipes as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.drink_recipes as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.external_menu_mappings as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.external_menu_mappings as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.external_menu_mappings as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.external_menu_mappings as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.guest_list_entries as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.guest_list_entries as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.guest_list_entries as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.guest_list_entries as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.guest_list_entries as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.guest_list_entries as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.guest_list_entries as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.guest_list_entries as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.ingredients as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.ingredients as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.ingredients as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.ingredients as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.inventory_counts as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.inventory_counts as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.inventory_counts as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.inventory_counts as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.inventory_items as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.inventory_items as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.inventory_items as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.inventory_items as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy inventory_items_staff on public.inventory_items as permissive for ALL to public using (private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum, 'chef'::user_roles_role_enum, 'barman'::user_roles_role_enum]));
create policy authenticated_delete_by_restaurant_manager on public.leave_requests as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.leave_requests as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.leave_requests as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.leave_requests as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.leave_requests as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.leave_requests as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.leave_requests as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.leave_requests as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.lineups as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.lineups as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.lineups as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.lineups as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.platform_connections as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.platform_connections as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.platform_connections as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.platform_connections as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.promoter_payments as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.promoter_payments as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.promoter_payments as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.promoter_payments as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.promoter_sales as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.promoter_sales as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.promoter_sales as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.promoter_sales as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.promoters as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.promoters as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.promoters as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.promoters as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.promoters as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.promoters as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.promoters as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.promoters as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.purchase_records as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.purchase_records as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.purchase_records as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.purchase_records as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.queue_entries as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.queue_entries as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.queue_entries as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.queue_entries as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.queue_entries as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.queue_entries as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.queue_entries as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.queue_entries as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.recipes as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.recipes as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.recipes as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.recipes as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy restaurant_integrations_staff on public.restaurant_integrations as permissive for ALL to public using (private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])) with check (private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]));
create policy authenticated_delete_by_restaurant_manager on public.shifts as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.shifts as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.shifts as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.shifts as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.stock_items as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.stock_items as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.stock_items as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.stock_items as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.stock_movements as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.stock_movements as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.stock_movements as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.stock_movements as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.supplier_item_mappings as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.supplier_item_mappings as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.supplier_item_mappings as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.supplier_item_mappings as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.suppliers as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.suppliers as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.suppliers as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.suppliers as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.tab_members as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_own_user_id on public.tab_members as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_own_user_id on public.tab_members as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_own_user_id on public.tab_members as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_own_user_id on public.tab_payments as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_own_user_id on public.tab_payments as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_own_user_id on public.tab_payments as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_own_user_id on public.tab_payments as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.tabs as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.tabs as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.tabs as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.tabs as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.unit_conversions as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.unit_conversions as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.unit_conversions as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.unit_conversions as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.vip_table_guests as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_own_user_id on public.vip_table_guests as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_own_user_id on public.vip_table_guests as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_own_user_id on public.vip_table_guests as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.vip_table_reservations as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.vip_table_reservations as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.vip_table_reservations as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.vip_table_reservations as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_by_restaurant_manager on public.waiter_calls as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_delete_own_user_id on public.waiter_calls as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_insert_by_restaurant_manager on public.waiter_calls as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_own_user_id on public.waiter_calls as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_select_by_restaurant on public.waiter_calls as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_select_own_user_id on public.waiter_calls as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_update_by_restaurant_manager on public.waiter_calls as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_update_own_user_id on public.waiter_calls as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid()))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR (user_id = auth.uid())));
create policy authenticated_delete_by_restaurant_manager on public.webhook_subscriptions as permissive for DELETE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_insert_by_restaurant_manager on public.webhook_subscriptions as permissive for INSERT to authenticated with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
create policy authenticated_select_by_restaurant on public.webhook_subscriptions as permissive for SELECT to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id)));
create policy authenticated_update_by_restaurant_manager on public.webhook_subscriptions as permissive for UPDATE to authenticated using ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum]))) with check ((private.has_any_app_role(ARRAY['admin'::text]) OR private.has_restaurant_role(restaurant_id, ARRAY['owner'::user_roles_role_enum, 'manager'::user_roles_role_enum])));
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.attendances to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.attendances to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.club_birthday_entries to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.club_birthday_entries to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.club_check_in_outs to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.club_check_in_outs to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.club_entries to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.club_entries to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.delivery_settlements to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.delivery_settlements to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.drink_recipes to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.drink_recipes to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.external_menu_mappings to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.external_menu_mappings to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.guest_list_entries to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.guest_list_entries to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.ingredient_prices to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.ingredient_prices to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.ingredient_suppliers to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.ingredient_suppliers to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.ingredients to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.ingredients to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.inventory_count_items to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.inventory_count_items to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.inventory_counts to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.inventory_counts to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.inventory_items to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.inventory_items to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.leave_requests to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.leave_requests to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.lineup_slots to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.lineup_slots to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.lineups to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.lineups to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.payment_splits to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.payment_splits to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.platform_connections to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.platform_connections to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.promoter_payments to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.promoter_payments to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.promoter_sales to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.promoter_sales to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.promoters to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.promoters to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.purchase_records to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.purchase_records to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.queue_entries to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.queue_entries to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.recipe_ingredients to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.recipe_ingredients to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.recipes to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.recipes to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.restaurant_integrations to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.restaurant_integrations to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.shifts to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.shifts to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.stock_items to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.stock_items to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.stock_movements to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.stock_movements to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.supplier_item_mappings to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.supplier_item_mappings to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.suppliers to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.suppliers to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tab_items to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tab_items to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tab_members to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tab_members to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tab_payments to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tab_payments to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tabs to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.tabs to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.unit_conversions to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.unit_conversions to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vip_table_guests to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vip_table_guests to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vip_table_reservations to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vip_table_reservations to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vip_table_tab_items to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vip_table_tab_items to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vip_table_tabs to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.vip_table_tabs to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.waiter_calls to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.waiter_calls to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.webhook_deliveries to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.webhook_deliveries to authenticated;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.webhook_subscriptions to anon;
grant DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE on public.webhook_subscriptions to authenticated;

commit;
