-- Captura dos objetos criados direto no banco de produção, fora das migrations.  (T-X-20)
--
-- Encontrados em 2026-09-14 comparando o catálogo do projeto eplivpvqemowmbivhfpx com as
-- migrations versionadas: tabelas, colunas, funções, gatilhos e índices.  Sem este arquivo,
-- `supabase db reset` produz um banco sem eles, e o CI testa um schema diferente do de
-- produção.
--
-- Tudo aqui é idempotente e reproduz a definição viva: aplicado em produção, não muda nada.
--
--   public."Projeto_Ativo"                         tabela da automação que mantém o projeto ativo no plano free
--   public.orders.order_number                      coluna + índice único parcial
--   private.assign_order_number()                   função do gatilho de número do pedido
--   orders_assign_order_number                      gatilho BEFORE INSERT em orders
--   public.restaurant_get_customer_crm(uuid, text)  RPC do CRM do restaurante
--   idx_customer_profiles_restaurant_segment        índice
--   idx_customer_profiles_restaurant_spent          índice
--   idx_reservations_metadata_gin                   índice

-- ---------------------------------------------------------------------------
-- Projeto_Ativo.  Sem política: nega tudo a anon e authenticated; a automação
-- escreve com service_role.
-- ---------------------------------------------------------------------------
create table if not exists public."Projeto_Ativo" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  "Ativo" text
);

comment on table public."Projeto_Ativo" is 'Usado na automação para deixar o projeto ativo no plano free';

alter table public."Projeto_Ativo" enable row level security;

-- ---------------------------------------------------------------------------
-- Número do pedido.
-- ---------------------------------------------------------------------------
alter table public.orders add column if not exists order_number text;

create unique index if not exists uq_orders_order_number
  on public.orders using btree (order_number)
  where order_number is not null;

create or replace function private.assign_order_number()
returns trigger
language plpgsql
set search_path to ''
as $function$
begin
  if new.order_number is null or btrim(new.order_number) = '' then
    new.order_number :=
      'NW-' ||
      to_char(coalesce(new.created_at, now()), 'YYMMDD') ||
      '-' ||
      upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12));
  end if;

  return new;
end;
$function$;

create or replace trigger orders_assign_order_number
  before insert on public.orders
  for each row execute function private.assign_order_number();

-- ---------------------------------------------------------------------------
-- CRM do restaurante.
--
-- Os grants reproduzem a ACL viva, que inclui `anon`.  A função barra anônimos por
-- `private.require_restaurant_role`, mas o grant a `anon` fica para revisão em T-F1-05.
-- ---------------------------------------------------------------------------
create or replace function public.restaurant_get_customer_crm(p_restaurant_id uuid, p_segment text default null::text)
returns jsonb
language plpgsql
stable security definer
set search_path to 'public', 'private', 'pg_temp'
as $function$
declare
  result jsonb;
begin
  perform private.require_restaurant_role(
    p_restaurant_id,
    array['owner','manager']::public.user_roles_role_enum[]
  );

  if p_segment is not null
     and p_segment not in ('new', 'regular', 'vip', 'dormant') then
    raise exception 'Invalid customer segment: %', p_segment
      using errcode = '22023';
  end if;

  with customer_rows as (
    select
      cp.id,
      cp.user_id,
      cp.restaurant_id,
      cp.total_visits,
      cp.total_spent,
      cp.avg_ticket,
      cp.last_visit_at,
      case
        when nullif(btrim(cp.favorite_items), '') is null then '[]'::jsonb
        else to_jsonb(
          regexp_split_to_array(
            cp.favorite_items,
            '[[:space:]]*[|][[:space:]]*'
          )
        )
      end as favorite_items,
      case
        when nullif(btrim(cp.dietary_preferences), '') is null then '[]'::jsonb
        else to_jsonb(
          regexp_split_to_array(
            cp.dietary_preferences,
            '[[:space:]]*[|][[:space:]]*'
          )
        )
      end as dietary_preferences,
      cp.segment,
      cp.birthday,
      cp.notes,
      cp.created_at,
      jsonb_build_object(
        'id', p.id,
        'full_name', p.full_name,
        'email', p.email,
        'phone', p.phone,
        'avatar_url', p.avatar_url
      ) as "user"
    from public.customer_profiles cp
    join public.profiles p on p.id = cp.user_id
    where cp.restaurant_id = p_restaurant_id
  ),
  all_customers as (
    select jsonb_build_object(
      'id', id,
      'user_id', user_id,
      'restaurant_id', restaurant_id,
      'total_visits', total_visits,
      'total_spent', total_spent,
      'avg_ticket', avg_ticket,
      'last_visit_at', last_visit_at,
      'favorite_items', favorite_items,
      'dietary_preferences', dietary_preferences,
      'segment', segment,
      'birthday', birthday,
      'notes', notes,
      'user', "user"
    ) as profile,
    segment,
    total_spent,
    created_at
    from customer_rows
  )
  select jsonb_build_object(
    'overview', jsonb_build_object(
      'segments', jsonb_build_object(
        'new', (select count(*) from all_customers where segment = 'new'),
        'regular', (select count(*) from all_customers where segment = 'regular'),
        'vip', (select count(*) from all_customers where segment = 'vip'),
        'dormant', (select count(*) from all_customers where segment = 'dormant')
      ),
      'total_customers', (select count(*) from all_customers),
      'top_customers', coalesce(
        (
          select jsonb_agg(profile order by total_spent desc)
          from (
            select profile, total_spent
            from all_customers
            order by total_spent desc
            limit 5
          ) top_five
        ),
        '[]'::jsonb
      )
    ),
    'customers', coalesce(
      (
        select jsonb_agg(profile order by total_spent desc, created_at desc)
        from all_customers
        where p_segment is null or segment = p_segment
      ),
      '[]'::jsonb
    )
  )
  into result;

  return result;
end;
$function$;

grant execute on function public.restaurant_get_customer_crm(uuid, text) to anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Índices.
-- ---------------------------------------------------------------------------
create index if not exists idx_customer_profiles_restaurant_segment
  on public.customer_profiles using btree (restaurant_id, segment);

create index if not exists idx_customer_profiles_restaurant_spent
  on public.customer_profiles using btree (restaurant_id, total_spent desc);

create index if not exists idx_reservations_metadata_gin
  on public.reservations using gin (metadata);
